name: docusecure
description: A blockchain-based document verification app

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.5.4
  http: ^0.13.4
  provider: ^6.0.0
